---
sudo: false
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=1.9.4

before_install:
 - apt-get update -qq
 - apt-get install -qq python-apt python-pycurl python-mysqldb
install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - echo -e 'localhost ansible_connection=local' > spec/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./spec/inventory' > ansible.cfg
script:
  - ansible-playbook --syntax-check spec/travis.yml
  - ansible-playbook --sudo -v --diff spec/travis.yml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
